### ISSUE TITLE
Accessing through LAN doesn't work with Android

### ISSUE THREAD

**Issue by parasiteoflife** [appdev/siyuan-unlock#10]
I've set up an access code and then enabled LAN access on the Android app, then I tried accessing using the IP and port and it asks me for the access code, after I enter it in Firefox nothing happens and I get a 404 error on the console, in Vivaldi it shows a Not Found message as it redirects to `http://192.168.18.111:6806/stage/build/desktop/?r={some-string-that-I-redacted-just-in-case}`

I've tried the same steps with the Windows app and it works there.

Btw the `{some-string-that-I-redacted-just-in-case}` that the desktop app redirects to is different than the one from the Android app.

**Comment by appdev** [comment]
For any issues related to functionality, please ask directly in the SiYuan repository. https://github.com/siyuan-note/siyuan
