### ISSUE TITLE
Portable version please

### ISSUE THREAD

**Issue by jimmy123j** [appdev/siyuan-unlock#12]
as title, hope can provide portable version, Thanks !!!

**Comment by pakeh2866** [comment]
是否支持IOS？

**Comment by jimmy123j** [comment]
我個人是 Windows 版，但如果版主願意可以連 IOS 的 Portable 一起製作，我想應該對很多人有幫助
主要是很多環境無法擅自決定安裝軟體，只能採用 Portable 版本
非常感謝版主

**Comment by appdev** [comment]
对iOS开发不熟，而且目前工作设备切换到了Linux所以暂时无法制作iOS版本



---Original---
From: ***@***.***&gt;
Date: Thu, Apr 25, 2024 16:41 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [appdev/siyuan-unlock] Portable version please (Issue #12)




 
我個人是 Windows 版，但如果版主願意可以連 IOS 的 Portable 一起製作，我想應該對很多人有幫助
 主要是很多環境無法擅自決定安裝軟體，只能採用 Portable 版本
 非常感謝版主

**Comment by jimmy123j** [comment]
那希望能至少有 Windows 版本的 Portable 版，感謝版主

**Comment by lmy138** [comment]
没有移动端同步个寂寞
