### ISSUE TITLE
安卓app 私服无法使用

### ISSUE THREAD

**Issue by chenxuan520** [appdev/siyuan-unlock#13]
![图片](https://github.com/appdev/siyuan-unlock/assets/77540051/28b4648d-0228-4052-844c-06168895153e)
1. 版本为103.0.5,手机开启私服功能
2. 电脑浏览器输入正确授权码之后电脑无法进入笔记

**Comment by appdev** [comment]
你可以先试试，官方原版可以吗？

**Comment by chenxuan520** [comment]
我试过官方原版没有问题

> 你可以先试试，官方原版可以吗？

**Comment by appdev** [comment]
等后面我更新一下Android 版本

**Comment by appdev** [comment]
修复了。可以使用最新Android 版本
