### ISSUE TITLE
若干功能咨询

### ISSUE THREAD

**Issue by Eyion** [appdev/siyuan-unlock#14]
1. 可以设置自己的图床吗？如R2
2. 可以用R2或webdav等进行同步吗？
3. 是否可以一键发布到WordPress等平台？

**Comment by appdev** [comment]
支持 Amazon S3 协议兼容的第三方云端存储服务，你说的 R2 也是支持的。
没有提供一键发布到WordPress ，支持插件系统，你可以自己写插件

**Comment by Eyion** [comment]
好的，谢谢。
另外，微信提醒是需要付费会员才能用的是吧

**Comment by appdev** [comment]
> 好的，谢谢。 另外，定时微信提醒和收集箱是需要付费会员才能用的是吧

不知道。你说的这两个功能我都没用过

**Comment by chenxuan520** [comment]
> 好的，谢谢。 另外，定时微信提醒和收集箱是需要付费会员才能用的是吧

这两个功能需要公众号后台的支持,需要服务器支持,超过了软件本身了,只能付费会员才能使用
