### ISSUE TITLE
希望能适配极空间NAS Docker部署

### ISSUE THREAD

**Issue by NewTrees** [appdev/siyuan-unlock#16]
思源笔记 Docker 镜像是使用的默认创建的普通用户 siyuan （uid 1000/gid 1000）来启动内核进程的，但极空间文件夹是 root 用户权限，当创建 docker 镜像时做了文件夹映射后，普通用户 siyuan 是没有权限在设置的目录下创建新的文件夹，所以导致镜像就会启动不成功，一直反复重启。

**Comment by appdev** [comment]
你可以先用root账号创建好文件夹，权限设置为777

**Comment by NewTrees** [comment]
怎么先用root账号创建好文件夹？极空间的docker只能先创建好容器后才能ssh进去，但是容器一直在重复重启中，ssh也没法进

**Comment by appdev** [comment]
没用过极空间，极空间不能SSH到主机吗？如果不能，你可以在UI界面创建好文件夹，然后在权限哪里给所有人管理这个文件夹的权限



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月21日(周三) 晚上10:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [appdev/siyuan-unlock] 希望能适配极空间NAS Docker部署 (Issue #16)




 
怎么先用root账号创建好文件夹？极空间的docker只能先创建好容器后才能ssh进去，但是容器一直在重复重启中，ssh也没法进

**Comment by NewTrees** [comment]
不能ssh进主机，UI界面创建的文件夹也不能分配权限，我看别的作者是改镜像的Dockerfile ，将启动用户改为 root 用户解决的

**Comment by appdev** [comment]
这个你修改一下docker启动命令就行了，不要适配的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月21日(周三) 晚上10:20
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [appdev/siyuan-unlock] 希望能适配极空间NAS Docker部署 (Issue #16)




 
不能ssh进主机，UI界面创建的文件夹也不能分配权限，我看别的作者是改镜像的Dockerfile ，将启动用户改为 root 用户解决的

**Comment by appdev** [comment]
删除 -u 1000:1000这行就是以root运行了

**Comment by NewTrees** [comment]
极空间安装docker镜像是没有改启动命令入口的，都是可视化的操作，所以无法删除 -u 1000:1000去启动
