### ISSUE TITLE
建议，可以删掉右上角的免费试用订阅链接吗

### ISSUE THREAD

**Issue by zzkuner** [appdev/siyuan-unlock#17]
建议，可以删掉右上角的免费试用订阅链接吗，或者把鼠标划过时候出现的字改成设置，不然看着有点违和

**Comment by NpTIme** [comment]
红色的图标和别的白色图标看着格格不入

**Comment by appdev** [comment]
我觉得应该是你安装的某个主题的问题
![2024_10_12_13_41_08](https://github.com/user-attachments/assets/37df7861-da01-43e4-b8bb-bc722f3c7aff)

**Comment by NpTIme** [comment]
你怎么设置的？

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by appdev** [comment]
没有任何设置，看看是不是你装的什么主题、插件影响的

**Comment by NpTIme** [comment]
啊？你应该也是装的这个项目吧，我怎么就有

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by appdev** [comment]
先排查一下你的插件跟主题吧

**Comment by NpTIme** [comment]
刚安装什么样就什么样

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Littleweisheit** [comment]
这软件要是可以离线激活就好了，价格也实惠。他那个账号还需要电费号码注册。😅

**Comment by Littleweisheit** [comment]
> 我觉得应该是你安装的某个主题的问题 ![2024_10_12_13_41_08](https://private-user-images.githubusercontent.com/9107717/375928931-37df7861-da01-43e4-b8bb-bc722f3c7aff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNTU3MDIsIm5iZiI6MTczMTA1NTQwMiwicGF0aCI6Ii85MTA3NzE3LzM3NTkyODkzMS0zN2RmNzg2MS1kYTAxLTQzZTQtYjhiYi1iYzcyMmYzYzdhZmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDhUMDg0MzIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmQ1NmJmYTg4Mjg2Y2M3YjcxMWVlYzFiYzQ1MGJmMGNmYjVjNmE3MDU1YzM4OThjNGU4ZDU4YmQ5NDYzMWEwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.WAdpK8YF1YkzEJryC8kWuKI1eRiWjmKlJfZB4tHz0PI)

我也有这个，系统Win11
![图片](https://github.com/user-attachments/assets/848acd2f-dbe4-48aa-a678-7a260abbb8b6)

**Comment by Littleweisheit** [comment]
可以用“移除按钮”这个插件移除，“微信提醒”那个按钮也可以移除。

**Comment by Littleweisheit** [comment]
ChatGPT 说把 `app/src/config/account.ts` 里
最后一行的 `document.getElementById("toolbarVIP").innerHTML = html;`
改为 `document.getElementById("toolbarVIP").innerHTML = "";`
希望 @appdev 能改一下

**Comment by appdev** [comment]
改了。
