### ISSUE TITLE
多谢多谢！

### ISSUE THREAD

**Issue by alexzeng2014** [appdev/siyuan-unlock#18]
太舒适了~~直接使用群晖webdav

**Comment by xqhjay** [comment]
> 太舒适了~~直接使用群晖webdav

你找到最新版的安卓包了吗？我看作者好像遗漏了

**Comment by appdev** [comment]
> > 太舒适了~~直接使用群晖webdav
> 
> 你找到最新版的安卓包了吗？我看作者好像遗漏了

可以看看以前发布的版本，每次更新其实没有太多的新内容。没有重大的更新就没有发android版本了
