### ISSUE TITLE
更新问题

### ISSUE THREAD

**Issue by Eyion** [appdev/siyuan-unlock#19]
操作系统版本：Windows 10 IoT 企业版 LTSC
目前软件版本：103.1.2
最新软件版本：103.1.6

自动下载更新安装包
启用后会每隔两小时自动检查版本更新，如果有更新版本则自动下载安装包并提示安装

开启上述功能后，实际未执行。
手动点击检查更新，也未有任何反应。

**Comment by appdev** [comment]
这只是一个基于官方的去除了用户登录功能的版本。其他所有功能都是维持官方原样的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月19日(周四) 中午11:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [appdev/siyuan-unlock] 更新问题 (Issue #19)




 
操作系统版本：Windows 10 IoT 企业版 LTSC
 目前软件版本：103.1.2
 最新软件版本：103.1.6
 
自动下载更新安装包
 启用后会每隔两小时自动检查版本更新，如果有更新版本则自动下载安装包并提示安装
 
开启上述功能后，实际未执行。
 手动点击检查更新，也未有任何反应。

**Comment by Eyion** [comment]
所以，自动更新和手动更新，都没有更改为本项目的相关地址，无法触发，只能下载新版进行覆盖安装？

**Comment by appdev** [comment]
是的，因为在修改的时候没有想过会频繁更新



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月19日(周四) 中午11:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [appdev/siyuan-unlock] 更新问题 (Issue #19)




 
所以，自动更新和手动更新，都没有更改为本项目的相关地址，无法触发，只能下载新版进行覆盖安装？

**Comment by Eyion** [comment]
懂了，谢谢。

**Comment by Eyion** [comment]
懂了，谢谢。
