### ISSUE TITLE
更新有点慢啊

### ISSUE THREAD

**Issue by DZL1943** [appdev/siyuan-unlock#24]

**Comment by appdev** [comment]
&nbsp;国庆出来玩了😎，应该也没有啥重大更新吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月5日(周六) 上午9:06
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [appdev/siyuan-unlock] 更新有点慢啊 (Issue #24)

**Comment by appdev** [comment]
更新了

**Comment by DZL1943** [comment]
> 更新了

安卓版忘更了?
