### ISSUE TITLE
webdav同步的问题

### ISSUE THREAD

**Issue by peng9461** [appdev/siyuan-unlock#25]
因为没有公网，所以是用的 stun 穿透，不方便的就是端口号会变动

所以使用了 CF 进行了重定向的操作，实现了下面的效果

在浏览器中输入 sy.siyuan.com 会自动跳转到 https://sy.webdav.siyuan.com:1234/

所以想请问，是否后续可以支持，在思源 webdav 同步中输入 sy.siyuan.com 即可完成同步的操作

目前如果在思源笔记中输入 https://sy.siyuan.com，会出现一个 main 的文件夹，并提示 同步失败：Remove main/siyuan/repo/lock-sync: 400，如果再加上资源路径的话，会提示 Authorize /: 401 (Provider: WebDAV)

这应该是思源笔记目前不支持的问题，在用的 komga+mihon，myplayer 均支持重定向之前的地址

**Comment by appdev** [comment]
这个问题你可以向思远官方提，看他们会不会修改 [Siyuan GitHub](https://github.com/siyuan-note/siyuan)
