### ISSUE TITLE
版本号不一致

### ISSUE THREAD

**Issue by Hhhls** [appdev/siyuan-unlock#27]
请问安卓端还跟进嘛，我现在用webdav同步，电脑版本是最新版本，和安卓版本不一致，同步没法使用，不知道是不是版本不一致导致的。

**Comment by appdev** [comment]
跟版本没有关系。安卓版使用，上次发布的版本也是能正常使用的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月25日(周五) 上午9:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [appdev/siyuan-unlock] 版本号不一致 (Issue #27)




 
请问安卓端还跟进嘛，我现在用webdav同步，电脑版本是最新版本，和安卓版本不一致，同步没法使用，不知道是不是版本不一致导致的。

**Comment by Hhhls** [comment]
好的，我再重新试一下，谢谢

**Comment by appdev** [comment]
更新了 Android 版本
