### ISSUE TITLE
Empty video link

### ISSUE THREAD

**Issue by neyuki** [appdev/siyuan-unlock#29]
After inserting video link and adding lets say youtube link to its assets, nothing going on. Showing just empty video box.

Tested under ArchLinux:

siyuan-103.1.9-linux
siyuan-103.1.10-linux

**Comment by appdev** [comment]
Please try to load it using IFrame block.

**Comment by appdev** [comment]
Given a URL like this - https://www.youtube.com/watch?v=AaZ_RSt0KP8&t=45s
Convert it to an embedded URL like this - https://www.youtube.com/embed/AaZ_RSt0KP8
