### ISSUE TITLE
页面UI错位

### ISSUE THREAD

**Issue by nico-0131** [appdev/siyuan-unlock#35]
![image](https://github.com/user-attachments/assets/683da027-bd85-4588-8e96-cba6f4b09a92)
![image](https://github.com/user-attachments/assets/4e7184a1-3df5-44d7-be06-10d0360eea8d)
![image](https://github.com/user-attachments/assets/12c6433b-70e9-4c84-9480-65d7eaf4b40b)
![image](https://github.com/user-attachments/assets/477622ee-68c9-4b35-bc41-5d5a7085c2f7)

**Comment by appdev** [comment]
换个主题还有问题吗？

**Comment by nico-0131** [comment]
> Owner

重新看了一下，是从正式版本覆盖安装之后出现的UI错位，重启几遍之后正常了
