### ISSUE TITLE
您好 可以交流一下安卓打包的流程吗？

### ISSUE THREAD

**Issue by uuuuuuuuuup** [appdev/siyuan-unlock#4]
我想自己打包一下安卓的包 可以请教一下 怎么打吗 谢谢啦

**Comment by appdev** [comment]
Android 打包已经写到脚本里了，先运行 https://github.com/appdev/siyuan-unlock/blob/master/scripts/android-build.sh
然后执行正常的Android 打包流程就可以了

**Comment by uuuuuuuuuup** [comment]
好滴 谢谢啦

**Comment by hanlihanshaobo** [comment]
> Android 打包已经写到脚本里了，先运行 https://github.com/appdev/siyuan-unlock/blob/master/scripts/android-build.sh 然后执行正常的Android 打包流程就可以了

mac是哪个脚本啊
