### ISSUE TITLE
大佬，还会继续更新嘛~

### ISSUE THREAD

**Issue by hyh6611** [appdev/siyuan-unlock#5]
大佬，还会继续更新嘛~

**Comment by nubya** [comment]
额，还等着大佬编译最新的win版本呢，看来是没希望了
关注的另一位去账号限制的大佬也弃坑了，可惜啊

**Comment by appdev** [comment]
会更新，只是一直没有啥大的变化，所以没有更。我主要是用 linux 、跟 docker 版本，Android 只是查看。Windows说实话电脑都没有。之前的Windows 还是在虚拟机里编译的。也没测试。
可能我用的功能比较少，感觉目前的版本已经满足需要了，所以更新周期会比较长，大概3-4周同步一次官方代码。官方基本上几天一个版本，实在跟不上🤣

**Comment by nubya** [comment]
我之前用的别的大佬的去账号版2.10.10，但是最近一两个月webdav同步一直提示网络错误；又找到你这里的win版2.10.11，同样提示网络错误无法同步，2.10.12安装后打开提示内核丢失。所以期待大佬编译个可用的win版，或者指点下该用啥IDE编译，我来下载你的源码，尝试自己编译一下
apk版目前正常……

**Comment by hyh6611** [comment]
> 会更新，只是一直没有啥大的变化，所以没有更。我主要是用 linux 、跟 docker 版本，Android 只是查看。Windows说实话电脑都没有。之前的Windows 还是在虚拟机里编译的。也没测试。 可能我用的功能比较少，感觉目前的版本已经满足需要了，所以更新周期会比较长，大概3-4周同步一次官方代码。官方基本上几天一个版本，实在跟不上🤣

感谢大佬的回答，期待大佬的下个版本😘

**Comment by appdev** [comment]
> 我之前用的别的大佬的去账号版2.10.10，但是最近一两个月webdav同步一直提示网络错误；又找到你这里的win版2.10.11，同样提示网络错误无法同步，2.10.12安装后打开提示内核丢失。所以期待大佬编译个可用的win版，或者指点下该用啥IDE编译，我来下载你的源码，尝试自己编译一下 apk版目前正常……

更新了win版本你可以试试

**Comment by hyh6611** [comment]
感谢大佬

> > 我之前用的别的大佬的去账号版2.10.10，但是最近一两个月webdav同步一直提示网络错误；又找到你这里的win版2.10.11，同样提示网络错误无法同步，2.10.12安装后打开提示内核丢失。所以期待大佬编译个可用的win版，或者指点下该用啥IDE编译，我来下载你的源码，尝试自己编译一下 apk版目前正常……
> 
> 更新了win版本你可以试试

感谢大佬
