### ISSUE TITLE
大佬，我部署之后没有端口号，看日志好像是目录权限不足

### ISSUE THREAD

**Issue by AlanWang2333** [appdev/siyuan-unlock#6]
-v /mnt/diskA/docker/siyuan:/siyuan/workspace \ # 上方创建的容器卷:映射容器内思源笔记的数据存放路径，与workspace保持一致
-p 6807:6806 \  # 思源笔记容器内起的端口
-u 1001:1000 \  # 官方文档中，使用普通用户创建
-e LANG=zh_CN.UTF-8 \  # 参考链接中，设置默认为中文(主要是为了说明文档，还是中文方便一点)
-e LC_ALL=zh_CN.UTF-8 \
--restart=always \  # 容器自动重启
-d --name="siyuanNote" \ # -d:容器后台启动，--name 设置容器名称
apkdv/siyuan-unlock \  # 使用的镜像源名称
--workspace=/siyuan/workspace/  # 官方设置的容器内的数据存放路径，要与上方保持一致
--accessAuthCode=Qwe4567890   

部署后没有生成端口号并且有如下日志
2024/02/02 04:41:24 create log file [/.config/siyuan/kernel.log] failed: open /.config/siyuan/kernel.log: no such file or directory
E 2024/02/02 04:41:24 working.go:227: create user home conf folder [/.config/siyuan] failed: mkdir /.config: permission denied
2024/02/02 04:41:26 create log dir [/.config/siyuan/] failed: mkdir /.config: permission denied
2024/02/02 04:41:26 create log file [/.config/siyuan/kernel.log] failed: open /.config/siyuan/kernel.log: no such file or directory

7 / 7

这些日志表明容器内部出现了权限问题，导致无法创建文件或目录。通常情况下，这是由于容器中运行的用户没有足够的权限来创建所需的文件或目录。

针对这个问题，你可以尝试以下几种方法：

更改容器中运行的用户权限： 你已经在 Docker 命令中使用了 -u 1001:1000 参数，这会将容器内的用户和用户组切换到指定的 UID 和 GID。确保指定的 UID 和 GID 有足够的权限来创建所需的文件或目录。你可以尝试将 -u 1001:1000 参数修改为适合的值。

挂载主机目录到容器中： 如果容器内的权限配置无法满足要求，你可以尝试将需要的目录挂载到主机上，并将其挂载到容器内部。例如，你可以将 /mnt/diskA/docker/siyuan 目录挂载到容器内部的 /siyuan/workspace 目录。

检查容器镜像配置： 确保容器镜像的配置正确，并且容器内的路径与你的期望一致。有时容器镜像可能会有默认的配置，需要根据实际情况进行调整。

查看日志和文档： 进一步查看容器的日志以及相关文档，了解更多关于容器权限配置的信息。可能会有特定的配置或步骤需要遵循。

根据以上方法，你可以尝试调整容器的配置，以解决权限问题并成功部署你的应用。

**Comment by appdev** [comment]
你需要给你的目录 /mnt/diskA/docker/siyuan 可读可写的权限



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月2日(周五) 凌晨4:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [appdev/siyuan-unlock] 大佬，我部署之后没有端口号，看日志好像是目录权限不足 (Issue #6)




 
-v /mnt/diskA/docker/siyuan:/siyuan/workspace \ # 上方创建的容器卷:映射容器内思源笔记的数据存放路径，与workspace保持一致
 -p 6807:6806 \  # 思源笔记容器内起的端口
 -u 1001:1000 \  # 官方文档中，使用普通用户创建
 -e LANG=zh_CN.UTF-8 \  # 参考链接中，设置默认为中文(主要是为了说明文档，还是中文方便一点)
 -e LC_ALL=zh_CN.UTF-8 
 --restart=always \  # 容器自动重启
 -d --name="siyuanNote" \ # -d:容器后台启动，--name 设置容器名称
 apkdv/siyuan-unlock \  # 使用的镜像源名称
 --workspace=/siyuan/workspace/  # 官方设置的容器内的数据存放路径，要与上方保持一致
 --accessAuthCode=Qwe4567890
 
部署后没有生成端口号并且有如下日志
 2024/02/02 04:41:24 create log file [/.config/siyuan/kernel.log] failed: open /.config/siyuan/kernel.log: no such file or directory
 E 2024/02/02 04:41:24 working.go:227: create user home conf folder [/.config/siyuan] failed: mkdir /.config: permission denied
 2024/02/02 04:41:26 create log dir [/.config/siyuan/] failed: mkdir /.config: permission denied
 2024/02/02 04:41:26 create log file [/.config/siyuan/kernel.log] failed: open /.config/siyuan/kernel.log: no such file or directory
 
7 / 7
 
这些日志表明容器内部出现了权限问题，导致无法创建文件或目录。通常情况下，这是由于容器中运行的用户没有足够的权限来创建所需的文件或目录。
 
针对这个问题，你可以尝试以下几种方法：
 
更改容器中运行的用户权限： 你已经在 Docker 命令中使用了 -u 1001:1000 参数，这会将容器内的用户和用户组切换到指定的 UID 和 GID。确保指定的 UID 和 GID 有足够的权限来创建所需的文件或目录。你可以尝试将 -u 1001:1000 参数修改为适合的值。
 
挂载主机目录到容器中： 如果容器内的权限配置无法满足要求，你可以尝试将需要的目录挂载到主机上，并将其挂载到容器内部。例如，你可以将 /mnt/diskA/docker/siyuan 目录挂载到容器内部的 /siyuan/workspace 目录。
 
检查容器镜像配置： 确保容器镜像的配置正确，并且容器内的路径与你的期望一致。有时容器镜像可能会有默认的配置，需要根据实际情况进行调整。
 
查看日志和文档： 进一步查看容器的日志以及相关文档，了解更多关于容器权限配置的信息。可能会有特定的配置或步骤需要遵循。
 
根据以上方法，你可以尝试调整容器的配置，以解决权限问题并成功部署你的应用。

**Comment by AlanWang2333** [comment]
不知道咋给他加权限🙈
我用他那个官方版的论坛，里面有一个帖子部署成功了，
https://ld246.com/article/1700220927172
但是他这个云同步要会员
![Screenshot_2024-02-02-07-39-45-310_com microsoft emmx beta-edit](https://github.com/appdev/siyuan-unlock/assets/58912611/4f8f9264-36f4-4b50-aeb8-429e251b7b01)

**Comment by appdev** [comment]
都是一样的。或者你把/mnt/diskA/docker/siyuan目录换成一个你访问不需要权限的目录。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月2日(周五) 上午7:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [appdev/siyuan-unlock] 大佬，我部署之后没有端口号，看日志好像是目录权限不足 (Issue #6)




 
不知道咋给他加权限🙈
 我用他那个官方版的论坛，里面有一个帖子部署成功了，
 https://ld246.com/article/1700220927172
 但是他这个云同步要会员
 Screenshot_2024-02-02-07-39-45-310_com.microsoft.emmx.beta-edit.jpg (view on web)

**Comment by AlanWang2333** [comment]
![Screenshot_2024-02-02-08-19-00-646_com sonelli juicessh](https://github.com/appdev/siyuan-unlock/assets/58912611/3d486bb8-dba5-4d81-8cdc-9860305f8935)
还是不行，给权限了

**Comment by appdev** [comment]
> ![Screenshot_2024-02-02-08-19-00-646_com sonelli juicessh](https://private-user-images.githubusercontent.com/58912611/301685838-3d486bb8-dba5-4d81-8cdc-9860305f8935.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NzQ4NjMsIm5iZiI6MTcwNjg3NDU2MywicGF0aCI6Ii81ODkxMjYxMS8zMDE2ODU4MzgtM2Q0ODZiYjgtZGJhNS00ZDgxLThjZGMtOTg2MDMwNWY4OTM1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDExNDkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNTU0N2UwN2UxMjYwYjQzMjMyYzI2ZmE2MWU0Y2VhZDA2ZGNiZWExZDc4MmQwOTQ2OTdmOTA0ZGNiNTU5YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zBaDWN4C3AIfivq-4aGWWhlpuIIHLaRdVPmCl4-gvDg) 还是不行，给权限了


# 后面的是注释，删掉#后面的在运行这个命令

**Comment by AlanWang2333** [comment]
`version: '3.7'

services:
  siyuan-unlock:
    container_name: siyuan-unlock
    image: apkdv/siyuan-unlock
    ports:
      - "6807:6806"
    volumes:
      - /mnt/diskA/docker/siyuan-unlock:/siyuan/workspace
    environment:
      - LANG=zh_CN.UTF-8
      - LC_ALL=zh_CN.UTF-8
    restart: always
    user: "root"
    command: ["--workspace=/siyuan/workspace/", "--accessAuthCode=Qwe4567890"]
    networks:
      - myNetwork

networks:
  myNetwork:
    external: true`
我改了一下用root运行，好了，原来的user1000不行，没权限，而且授予权限是在docker compose yml里面编辑的，而不是和我上面那样子，都部署完了再在命令里面输入
